### ISSUE TITLE
Can't search for Bedrolls

### ISSUE THREAD

**Issue by Mart-Bogdan** [MaxZiCode/ZiTools#4]
![20181205022148_1](https://user-images.githubusercontent.com/775038/49481680-a11fbe00-f834-11e8-9949-1ac90db6722b.jpg)
![20181205022158_1](https://user-images.githubusercontent.com/775038/49481684-a3821800-f834-11e8-8ed1-8ee65204690d.jpg)

**Comment by MaxZiCode** [comment]
I'll try to fix that in the next version, thanks.

**Comment by Mart-Bogdan** [comment]
@MaxZiCode thanks!
I believe it's not on;y bedrolls, but other unisntalled equipment/furniture, if I remember correctly, but won't be able to check soon.

**Comment by Mart-Bogdan** [comment]
I confirma that other "uinstalled" objects/items aren't being searched.
For example Heaters, it found installed ones, but not uninstalled.

![image](https://user-images.githubusercontent.com/775038/50742150-0722ab00-1210-11e9-8be4-fdd6a44e0729.png)

**Comment by MaxZiCode** [comment]
Fixed in v1.9.1
![image](https://user-images.githubusercontent.com/36173597/52085556-ce2ee980-25b5-11e9-8fa8-8a0c6de02063.png)

**Comment by Mart-Bogdan** [comment]
Cooool thanks!

**Comment by Mart-Bogdan** [comment]
@MaxZiCode, have you published it on Steam Workshop?
Seems not working for me.
